[project]
name = "pmbio-peer"
version = "1.3.0"
dependencies = [
  "numpy"
]

[build-system]
requires = [
  "setuptools>=61",
  "scikit-build",
  "cmake",
  "numpy",
  "ninja; platform_system!='Windows'",
  "swig"
]
build-backend = "setuptools.build_meta"
